name: macOS

on:
  pull_request:
  push:
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest]
        luaVersion: ["5.4.1", "5.1.5", "luajit-2.1.0-beta3"]
        luarocksVersion: ["3.5.0", "3.0.1"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: leafo/gh-actions-lua@v8
        with:
          luaVersion: ${{ matrix.luaVersion }}
      - uses: leafo/gh-actions-luarocks@v4
        with:
          luarocksVersion: ${{ matrix.luarocksVersion }}

      - name: Tests
        run: |
          luarocks install --local rockspecs/example1-1.0-1.rockspec
          lua -e "print(require(\"example1.hello\"))"
          lua -e "print(require(\"example1.test\"))"
          luarocks install --local rockspecs/example2-1.0-1.rockspec
          lua -e "print(require(\"example2.hello\"))"
          lua -e "print(require(\"example2.test\"))"
