name: Windows

on:
  pull_request:
  push:
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: branch@dev

      - name: Tests
        run: |
          Invoke-WebRequest "https://github.com/xmake-mirror/luarocks/releases/download/v3.5.0/luarocks-all-3.5.0-windows-64.zip" -UseBasicParsing -OutFile ./luarocks.zip
          Expand-Archive ./luarocks.zip -DestinationPath ./luarocks
          Push-Location ./luarocks
          ./luarocks install --local --verbose ../rockspecs/example1-1.0-1.rockspec
          $Env:LUA_CPATH = $(Resolve-Path C:/Users/runneradmin/AppData/Roaming/luarocks/lib/lua/5.3/example1/hello.dll)
          ./bin/lua -e "print(require('example1.hello'))"
          ./bin/lua -e "print(require('example1.test'))"
          ./luarocks install --local --verbose ../rockspecs/example2-1.0-1.rockspec
          $Env:LUA_CPATH = $(Resolve-Path C:/Users/runneradmin/AppData/Roaming/luarocks/lib/lua/5.3/example2/hello.dll)
          ./bin/lua -e "print(require('example2.hello'))"
          ./bin/lua -e "print(require('example2.test'))"
